# This is a one shot job to run our performance test and write the results out to a volume
apiVersion: batch/v1
kind: Job
metadata:
  name: gatling
spec:
  template:
    metadata:
      name: gatling
    spec:
      restartPolicy: Never
      containers:
      - name: gatling
        image: openig-gatling
        imagePullPolicy: IfNotPresent
        command: ["gatling.sh",  "-s", "perftest.IGPerfTest"]
        volumeMounts:
          - name: perftest-results
            mountPath: /opt/gatling/results
      volumes:
      - name: perftest-results
        hostPath:
          path: /data/perftest-results