# Deploys a small web server to view the gatling results
# This works by mounting the results directory on the same volume as gatling
kind: Pod
apiVersion: v1
metadata:
  name: web
  labels:
    name: web-results
spec:
    containers:
    - name: web
      image: httpd:alpine
      volumeMounts:
        - name: perftest-results
          mountPath: /usr/local/apache2/htdocs
    volumes:
    - name: perftest-results
      hostPath:
        path: /data/perftest-results

---
# expose results server
apiVersion: v1
kind: Service
metadata:
  name: web-results
spec:
  type: NodePort
  ports:
    - port: 80
      name:  port80
      targetPort: 80
  selector:
    name: web-results